### ISSUE TITLE
A couple of rule 404's

### ISSUE THREAD

**Issue by DanGamble89** [stylelint/stylelint.github.io#4]
These pages 404 on the 3.0 docs

* http://stylelint.io/?/src/rules/function-space-after/README.md
* http://stylelint.io/?/src/rules/rule-single-line-max-declarations/README.md

**Comment by jeddy3** [comment]
Oops. This was my bad. I forgot to update the list of rules in the docs when I renamed a couple of the rules.

It's fixed in [`3.0.3`](https://github.com/stylelint/stylelint/releases/tag/3.0.3) and should be showing up on stylelint.io

Thanks for reporting btw :)

**Comment by DanGamble89** [comment]
:+1: I feel a bit bad at the moment throwing issues all over the place, just exploring Stylelint & PostCSS as a whole :D

**Comment by jeddy3** [comment]
> I feel a bit bad at the moment throwing issues all over the place

No need to feel a bit bad. We really appreciate it when someone reports things :)
