### ISSUE TITLE
Links on homepage 404'ing

### ISSUE THREAD

**Issue by ntwb** [stylelint/stylelint.github.io#5]
e.g. Both the following links:
> To craft your own from the ground up, just learn about [some rules](http://stylelint.io/docs/user-guide/rules.md). All of the rules are off by default, so you only have to learn about the rules you want to turn on and enforce. That way you can start small, growing your config over time as you have a chance to explore more of the rules. Alternately, copy-paste [this example configuration](http://stylelint.io/docs/user-guide/rules.json), which lists all of stylelint's rules and their primary options, then remove (or turn off) the rules you don't want and edit the primary option of each rule to your liking.

The above links are:
• http://stylelint.io/docs/user-guide/rules.md
• http://stylelint.io/docs/user-guide/rules.json

Probably a few more about the place to check whilst creating a fix

**Comment by jeddy3** [comment]
@ntwb Thanks for reporting.

The interim site is really quite creaky...

I'll see what I can do about patching these two links up.

**Comment by ntwb** [comment]
I haven't yet taken a myself on a full tour of this repo, I'll try to do that in the next day or two.

No doubt when I take a look I'll end up looking at #3 at the same time :smirk: 

Will try and find a place amongst these issues where I can lend a hand...

**Comment by jeddy3** [comment]
Done.

**Comment by ntwb** [comment]
Sweet, thats one epic update :+1:

**Comment by davidtheclark** [comment]
Thanks, @jeddy3 .
